name: Skyclerk
options:
  bundleIdPrefix: com.cloudmanic
  deploymentTarget:
    iOS: "18.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    INFOPLIST_FILE: Skyclerk/Info.plist

targets:
  Skyclerk:
    type: application
    platform: iOS
    sources:
      - Skyclerk
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cloudmanic.skyclerk
        INFOPLIST_FILE: Skyclerk/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTS_MACCATALYST: false
        SWIFT_EMIT_LOC_STRINGS: "YES"
        SWIFT_STRICT_CONCURRENCY: minimal
    info:
      path: Skyclerk/Info.plist
      properties:
        CFBundleDisplayName: Skyclerk
        CFBundleName: Skyclerk
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        NSCameraUsageDescription: "To Take Photos and Video"
        NSPhotoLibraryUsageDescription: "To Pick Photos from Library"
        NSPhotoLibraryAddUsageDescription: "Store camera photos to camera"
        NSLocationWhenInUseUsageDescription: "To tag your ledger entries with location"
        NSLocationAlwaysUsageDescription: "To tag your ledger entries with location"
        NSMicrophoneUsageDescription: "To Record Audio With Video"
        ITSAppUsesNonExemptEncryption: false
